config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  get 'my-resumes', to: 'my_resumes#index'

  resources :jobs do
    resources :resumes
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can [:read, :create, :destroy], Resume, user:user
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
    enum status: %i[draft published completed]
    has_many :resumes
    belongs_to :user
end
  

app/models/resume.rb
class Resume < ApplicationRecord

  validates :cover_letter, presence: true
  validates :attachment, presence: true

  belongs_to :job
  belongs_to :user
  after_commit :remove_previously_stored_attachment, on: :update
  mount_uploader :attachment, AttachmentUploader
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :jobs
  has_many :resumes

  def applied_job?(job_id)
    resumes.find_by job_id: job_id
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  # add_flash_types :success, :warning, :danger, :info

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username email password current_password])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @jobs = Job.all 
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, ]
    # before_action :set_post, only: [:show, :edit, :update, :destory]
    load_and_authorize_resource
    # before_action :authenticate_user!, except: [:index, :show ]

    def index
      @job = Job.all.order(created_at: :desc)
    end
    
  
    def show; end
  
    def new
      @job = Job.new
    end
  
    def create
      
      @job = current_user.jobs.new(job_params)
      # authorize! :create, @job
      if @job.save
        redirect_to jobs_path, success: 'Job was successfully created.'
      else
        render :new
      end
    end
  
    def edit; end
  
    def update
      if @job.update(job_params)
        redirect_to jobs_path
      else
        render :edit
      end
    end
  
    def destroy
      @job.destroy
      redirect_to jobs_path
    end
  
    private

    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :description, :status)
    end
  end
  

app/controllers/my_resumes_controller.rb
class MyResumesController < ApplicationController
   #authorize_resource
    
    def index
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController

   before_action :authenticate_user! 
   authorize_resource

    def index
      @resumes = Resume.all.where(job_id: params[:job_id])
    end
  
    def show
      @resume = Resume.find params[:id]
      @resume.update_attribute(:is_seen, true) unless @resume.is_seen
      @resume
      # @job = Job.find(params[:job_id])
      # @resume = Resume.find(params[:id])
      # @resume.update_attribute : is_seen,true
    end
  
    def create
      @job = Job.find(params[:job_id])
      @resume  = @job.resumes.build(resume_params)
      @resume.user_id = current_user.id
      
      if @resume.save
        redirect_to jobs_path
      else
        redirect_to job_path params[:job_id]
      end
    end

    def destroy
      @resume = Resume.find(params[:id])
      @resume.destroy
      redirect_to job_path(params[:job_id])
    end
  
    private
  
    def resume_params
      params.require(:resume).permit(:cover_letter, :attachment)
    end
  
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/my_resumes_helper.rb
module MyResumesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/jobs/edit.html.erb
<h3>Edit Job</h3>


<%= form_for  @job do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :status %>
    <%= form.select :status, [:draft, :published, :completed] %>
  </div>

  <div>
    <%= form.submit 'Update Job' %>
  </div>
<% end %>

app/views/jobs/index.html.erb
<h1>Jobs List</h1>

 <% if can? [:update, :destroy], @job %>
  <%= link_to 'New Job', new_job_path, class: 'btn btn-primary' %>
<% end %>

<% @jobs.each do |job| %>

  <div class="card">
    <div class="card-body">
      <h5><%= job.title %></h5>

      <p><%= job.description %></p>
      <span class="badge badge-success">
        <%= job.status %>
      </span>
      <div>
        <%= link_to 'Show', job_path(job) , class: 'btn btn-sm btn-primary' %>
        

 <% if can? [:update, :destroy], job %>
          <%= link_to 'Edit', edit_job_path(job) ,class: 'btn btn-sm btn-warning' %>
          <%= link_to 'Delete', job_path(job), method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn btn-sm btn-danger'  %>
          <%= link_to 'Resumes', job_resumes_path(job),class: 'btn btn-sm btn-info'  %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/jobs/new.html.erb
<div class="row">
<h4>Create Job</h4>

    <div class="col-6 offset-3">
        <%= form_for @job do |form| %>
            <div class="mt-3">
                <%= form.label :title, class:'control-label' %>
                <%= form.text_field :title, class:'form-control' %>
            </div>

            <div class="mt-3">
                <%= form.label :description, class:'control-label' %>
                <%= form.text_area :description, class:'form-control' %>
            </div>

            <div class="mt-3">
                <%= form.label :status, class:'control-label' %>
                <%= form.select :status, [:draft, :published, :completed], class:'form-control' %>
            </div>

            <div class="mt-3">
                <%= form.submit 'Create Job', class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>

</div>

app/views/jobs/show.html.erb
<h4><%= @job.title %></h4>
<div> <%= @job.description %> </div>
<div> <%= @job.status %> </div>
<p>Created Date: <%= @job.created_at %></p>
  

<% if user_signed_in? && current_user.applied_job?(@job.id) %>
   <%= link_to 'Cancel Applied', [@job, current_user.applied_job?(@job.id)], method: :delete, data: { confirm: 'Are you sure?'}, calss: 'btn btn-danger' %>
<% else%>
    <h4>Apply Job</h4>
    <%= form_for [@job, @job.resumes.build] do |form| %>

          <div class="mt-3">
            <%= form.label :cover_letter, class: 'control-label' %>
            <%= form.text_area :cover_letter, class: 'form-control' %>
          </div>

          <div class="mt-3">
            <%= form.label :attachmet, class: 'control-label' %>
            <%= form.file_field :attachment, class: 'form-control' %>
          </div>

          <div class="mt-3">
            <%= form.submit 'Apply', class: 'btn btn-primary' %>
          </div> 
 
  <% end %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>

    <%= render 'shared/navbar' %>

    <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/my_resumes/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Job </th>
      <th>Email:</th>
      <th>Seen by Admin</th>
      <th>Applied At</th>
      <th>Action</th>
      
    </tr>
  </thead>
       
  <tbody>
    <tr>
     <% current_user.resumes.each do |resume| %>
          <% if resume.job %>
            <td><%= link_to resume.job.title, job_path(resume.job) %></td>
          <% end %>
          <td><%= resume.user.email %></td>
          <td><%= resume.is_seen ? 'Seen' : 'Not seen yet' %></td>
          <td><%= time_ago_in_words resume.created_at %></td>
          <td>
            <%= link_to 'Download', resume.attachment_url, download: '', target: :_blank %>
          </td>
       
        </tr>
        <%end%>
  </tbody>

</table>

app/views/resumes/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Job</th>
      <th>Email:</th>
      <th>Applied At</th>
      <th>Action</th>
    </tr>
  </thead>
 
  <tbody>

    <% @resumes.each do |resume| %>
        <tr>
          <% if resume.job %>
            <td><%= link_to resume.job.title, job_path(resume.job) %></td>
          <% end %>
          <td><%= resume.user.email %></td>
          <td><%= time_ago_in_words resume.created_at %></td>
          <td>
            <%= link_to 'Show', [resume.job, resume] , class: 'btn btn-sm btn-primary' %>
            <%= link_to 'Download', resume.attachment_url, download: '', target: :_blank %>
          </td>
        </tr>
    <% end %>
  </tbody>

</table>

app/views/resumes/show.html.erb
<h3>Resumes</h3>

<h3>Applicant Email : <%= @resume.user.email %> </h3>

<h5><%= @resume.cover_letter %></h5>

<%= link_to 'Download Resume', @resume.attachment_url, download: '', target: :_blank %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm">
  <div class="container">
    <%= link_to 'Job Board', root_path, class: 'navbar-brand' %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
         <% if can? [:update, :destory], @job %>
         <li class="nav-item">
          <%= link_to 'Jobs List', jobs_path, class: 'nav-link' %>
        </li>
        <% end %>
      </ul>

      <ul class="navbar-nav ms-auto">
        
        <% if user_signed_in? %>
          <% if can? :read, Resume%>
            <li class="nav-item active">
              <%= link_to 'My Resumes', my_resumes_path, class:'nav-link' %>
            </li>
          <% end %>

          <li class="nav-item active">
            <%= link_to current_user.username, edit_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class:'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item active">
            <%= link_to 'Signup', new_user_registration_path, class:'nav-link' %>
          </li>
          <li class="nav-item active">
            <%= link_to 'Login', new_user_session_path, class:'nav-link' %>
          </li>
        <% end %>
    </ul>
    </div>
  </div>
</nav> 